name: pic
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.0
  http: ^1.2.1
  webview_flutter: ^3.0.4
  shared_preferences: ^2.0.15
  shelf: ^1.3.0
  shelf_router: ^1.1.0
  shelf_cors_headers: ^0.1.5
  postgres: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
